name: Test Github actions

on:
  push:
    branches: [ 'master' ]

jobs:
  deploy:
    name: GoGo
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get list of folders with lambda functions
        run: |
          cd ${GITHUB_WORKSPACE}
          git diff --name-only HEAD HEAD~1 | 
          grep / | 
          cut -d/ -f1 | 
          sort -u | 
          xargs -I % find % -name *.java 2>/dev/null | 
          cut -d/ -f1